//! Manual FFI definitions for FFmpeg's hwcontext_vulkan.h.
//!
//! These are NOT generated by bindgen because rusty_ffmpeg excludes hwcontext_vulkan.h.
//! Struct layouts match FFmpeg 8 (libavutil 60.x) on 64-bit platforms.

#![allow(non_camel_case_types, dead_code)]

use std::ffi::{c_char, c_int, c_void};

use ash::vk;

/// AV_NUM_DATA_POINTERS from FFmpeg's frame.h
const AV_NUM_DATA_POINTERS: usize = 8;

/// `AVVulkanDeviceQueueFamily` from hwcontext_vulkan.h
#[repr(C)]
#[derive(Copy, Clone, Default)]
pub(crate) struct AVVulkanDeviceQueueFamily {
    pub idx: c_int,
    pub num: c_int,
    pub flags: u32,      // VkQueueFlagBits
    pub video_caps: u32, // VkVideoCodecOperationFlagBitsKHR
}

/// Placeholder for `VkPhysicalDeviceFeatures2`.
/// Real struct contains sType(4) + pad(4) + pNext(8) + VkPhysicalDeviceFeatures(55*u32=220) = 236,
/// padded to 240 bytes for 8-byte alignment.
#[repr(C, align(8))]
#[derive(Copy, Clone)]
pub(crate) struct VkPhysicalDeviceFeatures2Pad {
    _data: [u8; 240],
}

impl Default for VkPhysicalDeviceFeatures2Pad {
    fn default() -> Self {
        Self { _data: [0u8; 240] }
    }
}

/// `AVVulkanDeviceContext` from hwcontext_vulkan.h (FFmpeg 8, libavutil 60.x, 64-bit).
///
/// The deprecated queue fields (FF_API_VULKAN_FIXED_QUEUES) are present because
/// LIBAVUTIL_VERSION_MAJOR = 60 < 61.
#[repr(C)]
pub(crate) struct AVVulkanDeviceContext {
    pub alloc: *const c_void,
    pub get_proc_addr: vk::PFN_vkGetInstanceProcAddr,
    pub inst: vk::Instance,
    pub phys_dev: vk::PhysicalDevice,
    pub act_dev: vk::Device,
    pub device_features: VkPhysicalDeviceFeatures2Pad,
    pub enabled_inst_extensions: *const *const c_char,
    pub nb_enabled_inst_extensions: c_int,
    _pad1: c_int,
    pub enabled_dev_extensions: *const *const c_char,
    pub nb_enabled_dev_extensions: c_int,
    // Deprecated queue fields (FF_API_VULKAN_FIXED_QUEUES):
    pub queue_family_index: c_int,
    pub nb_graphics_queues: c_int,
    pub queue_family_tx_index: c_int,
    pub nb_tx_queues: c_int,
    pub queue_family_comp_index: c_int,
    pub nb_comp_queues: c_int,
    pub queue_family_encode_index: c_int,
    pub nb_encode_queues: c_int,
    pub queue_family_decode_index: c_int,
    pub nb_decode_queues: c_int,
    _pad2: c_int,
    pub lock_queue: *const c_void,
    pub unlock_queue: *const c_void,
    pub qf: [AVVulkanDeviceQueueFamily; 64],
    pub nb_qf: c_int,
    _tail_pad: c_int,
}

/// `AVVkFrame` from hwcontext_vulkan.h.
///
/// NOTE: FFmpeg says "the size of this structure is not part of the ABI".
/// We only read fields, never allocate this ourselves.
#[repr(C)]
pub(crate) struct AVVkFrame {
    pub img: [vk::Image; AV_NUM_DATA_POINTERS],
    pub tiling: u32, // VkImageTiling
    _pad0: u32,
    pub mem: [vk::DeviceMemory; AV_NUM_DATA_POINTERS],
    pub size: [usize; AV_NUM_DATA_POINTERS],
    pub flags: u32, // VkMemoryPropertyFlagBits
    // No padding here: both flags and access are u32, so access is already 4-byte aligned.
    // Rust's #[repr(C)] inserts padding between layout and sem automatically (for 8-byte alignment).
    pub access: [u32; AV_NUM_DATA_POINTERS],
    pub layout: [u32; AV_NUM_DATA_POINTERS],
    pub sem: [vk::Semaphore; AV_NUM_DATA_POINTERS],
    pub sem_value: [u64; AV_NUM_DATA_POINTERS],
    pub internal: *mut c_void,
    pub offset: [isize; AV_NUM_DATA_POINTERS],
    pub queue_family: [u32; AV_NUM_DATA_POINTERS],
}
